# Generated by Django 4.2.5 on 2023-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0002_remove_blogpost_comments_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.CharField(default=None, max_length=300),
        ),
    ]
