# Generated by Django 4.2.5 on 2023-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0003_alter_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(upload_to="blog_images/"),
        ),
    ]
