# Generated by Django 4.2.5 on 2023-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0004_blogpost_thumbnail_alter_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="blog_thumbnails/"),
        ),
    ]
