# Generated by Django 4.2.5 on 2023-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0009_alter_blogpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=models.TextField(blank=True, default="None", null=True),
        ),
    ]
