# Generated by Django 4.2.5 on 2023-10-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0010_alter_blogpost_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="description",
        ),
    ]
