# Generated by Django 4.2.5 on 2023-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0011_remove_blogpost_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="description",
            field=models.TextField(default="None"),
        ),
    ]
