# Generated by Django 4.2.5 on 2023-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0012_blogpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(max_length=300, to="blogapi.tag"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
